spring.application.name=barboapp
spring.data.mongodb.uri=mongodb+srv://barbo:abcddef@cluster0.xvuzuwv.mongodb.net/?appName=Cluster02
spring.data.mongodb.database=barbo_db

# JWT
jwt.secret=barboSuperSecretKey12345678
jwt.expiration=8630000
