spring.application.name=barboapp
spring.data.mongodb.uri=mongodb+srv://barbouser:BarboUser%402611@cluster0.xvuzuwv.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=barbo_db

# JWT
jwt.secret=barboSuperSecretKey1234567890ABCDEFbarboSuperSecretKey1234567890ABCDEF
jwt.expiration=86400000